### ISSUE TITLE
Add support for SIOC ontology

### ISSUE THREAD

**Issue by ianconsolata** [inrupt/solid-common-vocab-rdf#133]
### Search terms you've used
SIOC

### Feature suggestion
The SIOC (https://www.w3.org/Submission/sioc-spec/) vocab should be included in this library.

### Expected functionality/enhancement
I can import `SIOC`, or an inrupt specific subset, the same way I import FOAF and other common vocabs.

### Actual functionality/enhancement

This vocab is not currently listed.

### Use Cases

There are many vocabularies out there, and not all of them deserve to be packaged in this library as common vocab. However, SIOC seems like an omission here. It is a very useful ontology, especially for interlinking online communities and social spaces. Since Solid's goal is to help provide interoperability between online communities, these seems like a natural extension to include and encourage others to use.

**Comment by pmcb55** [comment]
Added SIOC long ago, so closing this issue (with thanks, again!).
